# Generated by Django 5.0.3 on 2024-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart_orders_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('kg', 'kg'), ('Number', 'Number'), ('Litre', 'Litre'), ('Packet', 'Packet'), ('Bottle', 'Bottle')], max_length=200),
        ),
    ]
