# Generated by Django 5.0.3 on 2024-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_products_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('packet', 'packet'), ('bottle', 'bottle'), ('tin', 'tin'), ('dozen', 'dozen'), ('cownumber', 'cownumber'), ('goatnumber', 'goatnumber'), ('chickennumber', 'chickennumber'), ('pignumber', 'pignumber'), ('ducknumber', 'ducknumber'), ('rabbitnumber', 'rabbitnumber'), ('horsenumber', 'horsenumber')], max_length=200),
        ),
    ]
