# Generated by Django 5.0.3 on 2024-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_products_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
